Repository TeamHous/Hous-Server, pull requests merged in 2022-07, with the labels that each got.

#2 컬렉션 생성
  src/interfaces/check/CheckInfo.ts
  src/interfaces/event/EventInfo.ts
  src/interfaces/room/RoomInfo.ts
  src/interfaces/rule/RuleInfo.ts
  src/interfaces/rulecategory/RuleCategoryInfo.ts
  src/interfaces/type/TypeInfo.ts
  src/interfaces/user/UserInfo.ts
  src/loaders/db.ts
  src/models/Check.ts
  src/models/Event.ts
  src/models/Room.ts
  src/models/Rule.ts
  src/models/RuleCategory.ts
  src/models/Type.ts
  src/models/User.ts
Labels: ✨ Feature, 🐻‍❄️ 혁준 🐻‍❄️

#7 #6 [mod] 에러 핸들링 수정 및 잘못된 경로에 대한 에러 추가
  src/controllers/UserController.ts
  src/error/errorGenerator.ts
  src/error/generalErrorHandler.ts
  src/index.ts
  src/middleware/auth.ts
  src/modules/responseMessage.ts
  src/modules/statusCode.ts
  src/services/UserService.ts
Labels: 🔧 Fix, 🐣 혜정 🐣

#8 회원가입, 로그인 기능 추가
  .eslintrc.js
  .prettierrc.json
  package-lock.json
  src/controllers/AuthController.ts
  src/controllers/UserController.ts
  src/controllers/index.ts
  src/error/errorGenerator.ts
  src/error/generalErrorHandler.ts
  src/errors/errorGenerator.ts
  src/errors/generalErrorHandler.ts
  src/index.ts
  src/interfaces/auth/LoginDto.ts
  src/interfaces/auth/SignupDto.ts
  src/interfaces/user/UserCreateDto.ts
  src/interfaces/user/UserSignInDto.ts
  src/middleware/auth.ts
  src/models/Check.ts
  src/models/Event.ts
  src/models/RuleCategory.ts
  src/modules/responseMessage.ts
  src/modules/util.ts
  src/routes/AuthRouter.ts
  src/routes/UserRouter.ts
  src/routes/index.ts
  src/services/AuthService.ts
  src/services/UserService.ts
  src/services/index.ts
Labels: ✨ Feature, 🐻‍❄️ 혁준 🐻‍❄️

#11 log 출력을 위한 라이브러리 및 설정파일 추가
  package-lock.json
  package.json
  src/config/logger.ts
  src/errors/generalErrorHandler.ts
  src/index.ts
  src/loaders/db.ts
  src/middleware/auth.ts
Labels: ✨ Feature, ⚙ Setting, 🐣 혜정 🐣

#14 방 생성 기능
  src/controllers/RoomController.ts
  src/controllers/index.ts
  src/modules/jwtHandler.ts
  src/modules/responseMessage.ts
  src/routes/RoomRouter.ts
  src/routes/index.ts
  src/services/RoomService.ts
  src/services/RoomServiceUtils.ts
  src/services/UserService.ts
  src/services/index.ts
Labels: ✨ Feature, 🐻‍❄️ 혁준 🐻‍❄️

#20 #19 [fix] 컬렉션 수정
  src/controllers/UserController.ts
  src/interfaces/check/CheckInfo.ts
  src/interfaces/event/EventInfo.ts
  src/interfaces/room/RoomInfo.ts
  src/interfaces/rule/RuleInfo.ts
  src/interfaces/rulecategory/RuleCategoryInfo.ts
  src/interfaces/user/UserInfo.ts
  src/middleware/auth.ts
  src/models/Check.ts
  src/models/Event.ts
  src/models/Room.ts
  src/models/Rule.ts
  src/models/RuleCategory.ts
  src/models/User.ts
  src/services/UserService.ts
Labels: 😸 연주 😸, 🐻‍❄️ 혁준 🐻‍❄️, 🔧 Fix, 🐣 혜정 🐣

#23 #13 [feat] 규칙 카테고리 추가 api 구현
  src/controllers/RuleController.ts
  src/controllers/index.ts
  src/interfaces/rulecategory/RuleCategoryCreateDto.ts
  src/interfaces/rulecategory/RuleCategoryInfo.ts
  src/interfaces/rulecategory/RuleCategoryResponseDto.ts
  src/modules/checkObjectIdValidation.ts
  src/modules/responseMessage.ts
  src/routes/RoomRouter.ts
  src/services/RuleService.ts
  src/services/index.ts
Labels: ✨ Feature, 😸 연주 😸

#24 나의 프로필 조회 api 구현
  src/controllers/UserController.ts
  src/interfaces/user/UserResponseDto.ts
  src/modules/responseMessage.ts
  src/routes/UserRouter.ts
  src/services/UserService.ts
  src/services/UserServiceUtils.ts
Labels: ✨ Feature, 🐣 혜정 🐣

#29 방 참가 api 수정
  src/controllers/RoomController.ts
  src/interfaces/room/CreateRoomDto.ts
  src/interfaces/room/JoinRoomDto.ts
  src/interfaces/room/RoomCreateDto.ts
  src/interfaces/room/RoomJoinDto.ts
  src/interfaces/room/RoomResponseDto.ts
  src/modules/checkObjectIdValidation.ts
  src/modules/responseMessage.ts
  src/routes/RoomRouter.ts
  src/services/RoomService.ts
  src/services/RuleService.ts
Labels: ✨ Feature, 🐻‍❄️ 혁준 🐻‍❄️, 🔧 Fix

#33 CI/CD를 위한 파일 추가
  .github/workflows/deploy.yml
  appspec.yml
  ecosystem.json
  package.json
  scripts/after-deploy.sh
Labels: ✨ Feature, 🐻‍❄️ 혁준 🐻‍❄️

#32 [fix] 수정 성공 시, 수정 내용 및 200으로 보내주도록 수정
  src/controllers/UserController.ts
  src/interfaces/user/UserUpdateResponseDto.ts
  src/modules/responseMessage.ts
  src/services/UserService.ts
  src/services/UserServiceUtils.ts
Labels: 🔧 Fix, 🐣 혜정 🐣

#31 규칙 카테고리 수정 api 구현
  src/controllers/RuleController.ts
  src/interfaces/rulecategory/RuleCategoryResponseDto.ts
  src/interfaces/rulecategory/RuleCategoryUpdateDto.ts
  src/modules/responseMessage.ts
  src/routes/RoomRouter.ts
  src/services/RuleService.ts
  src/services/RuleServiceUtils.ts
Labels: ✨ Feature, 😸 연주 😸

#35 #34 [fix] rooms 컬렉션 수정
  src/interfaces/room/RoomInfo.ts
  src/models/Room.ts
Labels: 😸 연주 😸, 🐻‍❄️ 혁준 🐻‍❄️, 🔧 Fix, 🐣 혜정 🐣

#39 사용자 정보 수정 api 수정
  src/modules/checkValidUtils.ts
  src/modules/limitNum.ts
  src/modules/responseMessage.ts
  src/routes/UserRouter.ts
  src/services/UserService.ts
  src/services/UserServiceUtils.ts
Labels: 🔧 Fix, 🐣 혜정 🐣

#41 방 관련 api 수정
  src/controllers/RoomController.ts
  src/interfaces/room/RoomCreateDto.ts
  src/interfaces/room/RoomJoinResponseDto.ts
  src/interfaces/room/RoomResponseDto.ts
  src/models/Room.ts
  src/models/User.ts
  src/routes/RoomRouter.ts
  src/services/RoomService.ts
  src/services/RoomServiceUtils.ts
Labels: 🐻‍❄️ 혁준 🐻‍❄️, 🔧 Fix

#43 이벤트 생성하기 api 구현
  src/controllers/EventController.ts
  src/controllers/index.ts
  src/interfaces/event/EventCreateDto.ts
  src/interfaces/event/EventCreateResponseDto.ts
  src/modules/IconType.ts
  src/modules/isIconType.ts
  src/modules/responseMessage.ts
  src/routes/RoomRouter.ts
  src/services/EventService.ts
  src/services/EventServiceUtils.ts
  src/services/index.ts
Labels: ✨ Feature, 🐣 혜정 🐣

#47 방 생성 api 수정
  package.json
  src/models/Room.ts
  src/services/RoomService.ts
Labels: 🐻‍❄️ 혁준 🐻‍❄️, 🔧 Fix

#48 #44 [fix] 규칙 카테고리 추가/수정 api에 CategoryIcon 체크 로직 추가
  src/controllers/EventController.ts
  src/modules/IconType.ts
  src/modules/checkIconType.ts
  src/modules/isIconType.ts
  src/modules/responseMessage.ts
  src/services/RuleService.ts
Labels: 😸 연주 😸, 🔧 Fix

#51 [feat] 이벤트 수정하기 api 구현
  src/controllers/AuthController.ts
  src/controllers/EventController.ts
  src/controllers/RoomController.ts
  src/interfaces/event/EventCreateDto.ts
  src/interfaces/event/EventCreateResponseDto copy.ts
  src/interfaces/event/EventUpdateDto.ts
  src/modules/responseMessage.ts
  src/routes/RoomRouter.ts
  src/services/EventService.ts
  src/services/EventServiceUtils.ts
  src/services/RuleService.ts
Labels: 🔧 Fix, 🐣 혜정 🐣

#52 50 [feat] 설정 조회하기 api 구현
  src/controllers/RuleController.ts
  src/controllers/UserController.ts
  src/interfaces/user/UserSettingResponseDto.ts
  src/routes/UserRouter.ts
  src/services/RuleService.ts
  src/services/RuleServiceUtils.ts
  src/services/UserService.ts
Labels: ✨ Feature, 😸 연주 😸

#55 #53 [feat] 이벤트 삭제하기 api 구현
  src/controllers/EventController.ts
  src/modules/responseMessage.ts
  src/routes/RoomRouter.ts
  src/services/EventService.ts
Labels: ✨ Feature, 🐣 혜정 🐣

#56 #54 [feat] 알림 설정 수정하기 api 구현
  src/controllers/UserController.ts
  src/interfaces/user/UsuerNotificationStateUpdateDto.ts
  src/modules/responseMessage.ts
  src/routes/UserRouter.ts
  src/services/UserService.ts
Labels: ✨ Feature, 😸 연주 😸

#57 #49 [feat] 규칙 1개 추가 api 구현
  src/controllers/RuleController.ts
  src/interfaces/rule/RuleCreateDto.ts
  src/interfaces/rule/RuleResponseDto.ts
  src/modules/checkValidUtils.ts
  src/modules/responseMessage.ts
  src/routes/RoomRouter.ts
  src/services/AuthService.ts
  src/services/RuleService.ts
Labels: ✨ Feature, 🐻‍❄️ 혁준 🐻‍❄️

#60 #59 [feat] 룸메이트 정보 조회 api 구현
  src/controllers/UserController.ts
  src/interfaces/event/EventUpdateResponseDto.ts
  src/interfaces/user/HomieResponseDto.ts
  src/interfaces/user/UserResponseDto.ts
  src/middleware/auth.ts
  src/modules/responseMessage.ts
  src/routes/UserRouter.ts
  src/services/EventService.ts
  src/services/UserService.ts
Labels: ✨ Feature, 🔧 Fix, 🐣 혜정 🐣

#66 #61 [feat] 규칙 생성 시 조회 api 구현
  src/controllers/RuleController.ts
  src/interfaces/rule/RuleCreateInfoResponseDto.ts
  src/modules/responseMessage.ts
  src/routes/RoomRouter.ts
  src/services/EventService.ts
  src/services/RuleService.ts
  src/services/UserService.ts
Labels: ✨ Feature, 😸 연주 😸

#65 #64 [feat] 규칙 1개 조회 api 구현
  src/controllers/RuleController.ts
  src/interfaces/rule/RuleReadInfoResponseDto.ts
  src/modules/responseMessage.ts
  src/routes/RoomRouter.ts
  src/services/RuleService.ts
  src/services/RuleServiceUtils.ts
Labels: ✨ Feature, 🐻‍❄️ 혁준 🐻‍❄️

#68 #67 [fix] 규칙 이름 중복 체크 추가
  src/controllers/RuleController.ts
  src/modules/responseMessage.ts
  src/services/RuleService.ts
Labels: 🐻‍❄️ 혁준 🐻‍❄️, 🔧 Fix

#77 규칙 생성 시 조회 api 수정
  src/controllers/RuleController.ts
  src/services/RuleService.ts
Labels: 😸 연주 😸, 🔧 Fix

#79 규칙 카테고리 추가/수정, 규칙 생성 시 조회에서 접근 권한 검사 추가
  src/modules/responseMessage.ts
  src/services/RuleService.ts
  src/services/RuleServiceUtils.ts
Labels: 😸 연주 😸, 🔧 Fix

#80 #72 [feat] 들어간 방 id 조회 api 구현
  src/controllers/RoomController.ts
  src/routes/RoomRouter.ts
  src/services/RoomService.ts
Labels: ✨ Feature, 🐻‍❄️ 혁준 🐻‍❄️

#70 [feat] 홈화면 조회 api 및 기타 수정사항 반영
  src/controllers/RoomController.ts
  src/interfaces/room/HomeResponseDto.ts
  src/models/Check.ts
  src/modules/responseMessage.ts
  src/routes/RoomRouter.ts
  src/services/EventService.ts
  src/services/EventServiceUtils.ts
  src/services/RoomService.ts
  src/services/RoomServiceUtils.ts
  src/services/UserService.ts
Labels: ✨ Feature, 🔧 Fix, 🐣 혜정 🐣

#85 규칙 카테고리 삭제 api 구현
  src/controllers/RuleController.ts
  src/modules/responseMessage.ts
  src/routes/RoomRouter.ts
  src/services/RuleService.ts
Labels: ✨ Feature, 😸 연주 😸

#88 규칙 생성/삭제, 규칙 카테고리 삭제 api 수정 (규칙 개수 제한)
  src/interfaces/room/RoomInfo.ts
  src/interfaces/rulecategory/RuleCategoryInfo.ts
  src/interfaces/rulecategory/RuleCategoryResponseDto.ts
  src/models/Room.ts
  src/models/RuleCategory.ts
  src/services/RuleService.ts
Labels: 😸 연주 😸, 🔧 Fix

#91 #83 [feat] 방 퇴사 api 구현
  src/controllers/RoomController.ts
  src/modules/responseMessage.ts
  src/routes/RoomRouter.ts
  src/services/RoomService.ts
  src/services/RoomServiceUtils.ts
Labels: ✨ Feature, 🐻‍❄️ 혁준 🐻‍❄️

#93 #92 [docs] Readme.md 수정
  README.md
Labels: 😸 연주 😸, 📃 Docs, 🐻‍❄️ 혁준 🐻‍❄️, 🐣 혜정 🐣

#96 #95 [feat] 이벤트 조회 api 구현
  src/controllers/EventController.ts
  src/interfaces/event/EventCreateResponseDto.ts
  src/interfaces/event/EventResponseDto.ts
  src/interfaces/event/EventUpdateResponseDto.ts
  src/interfaces/room/HomeResponseDto.ts
  src/modules/responseMessage.ts
  src/routes/RoomRouter.ts
  src/services/EventService.ts
  src/services/RoomService.ts
Labels: ✨ Feature, 🐣 혜정 🐣

#94 #87 [fix] 홈조회 시 이벤트 내 모든 내용 보이도록 수정
  src/interfaces/event/EventCreateResponseDto.ts
  src/interfaces/event/EventResponseDto.ts
  src/interfaces/event/EventUpdateResponseDto.ts
  src/interfaces/room/HomeResponseDto.ts
  src/services/RoomService.ts
Labels: ✨ Feature, 🔧 Fix, 🐣 혜정 🐣

#98 #97 [fix] 시간데이터 저장 시 그대로, DB에서 가져올 시 9시간 더해서 가져오도록 통일
  README.md
  src/interfaces/room/HomeResponseDto.ts
  src/services/EventService.ts
  src/services/RoomService.ts
  src/services/UserService.ts
Labels: 🔧 Fix, 🐣 혜정 🐣

#99 규칙 카테고리별 규칙 조회 api 구현
  src/controllers/RuleController.ts
  src/interfaces/rule/RulesByCategoryResponseDto.ts
  src/interfaces/user/UserInfo.ts
  src/models/User.ts
  src/modules/limitNum.ts
  src/modules/responseMessage.ts
  src/routes/RoomRouter.ts
  src/services/RuleService.ts
Labels: ✨ Feature, 😸 연주 😸

#103 오늘의 임시 담당자 설정 api 구현
  src/controllers/RuleController.ts
  src/interfaces/rule/RuleInfo.ts
  src/interfaces/rule/TmpRuleMembersUpdateDto.ts
  src/interfaces/rule/TmpRuleMembersUpdateResponseDto.ts
  src/models/Rule.ts
  src/modules/responseMessage.ts
  src/routes/RoomRouter.ts
  src/services/RuleService.ts
Labels: ✨ Feature, 😸 연주 😸

#106 #105 [fix] 날짜 관련 통일
  src/services/EventService.ts
  src/services/RoomService.ts
  src/services/RuleService.ts
Labels: 🐻‍❄️ 혁준 🐻‍❄️, 🔧 Fix

#108 #107 [feat] 규칙 홈화면 나의 to-do api 구현
  src/controllers/RuleController.ts
  src/interfaces/rule/RuleMyTodoResponseDto.ts
  src/modules/responseMessage.ts
  src/routes/RoomRouter.ts
  src/services/RuleService.ts
Labels: ✨ Feature, 🐻‍❄️ 혁준 🐻‍❄️

#112 방 생성 테스트
  .github/workflows/deploy.yml
  package.json
  test/RoomService.spec.ts
Labels: 🐻‍❄️ 혁준 🐻‍❄️, ✅ Test

#114 #113 [test] 방 참가하기 테스트 추가
  .github/workflows/deploy.yml
  src/config/index.ts
  src/config/logger.ts
  src/index.ts
  src/loaders/db.ts
  test/RoomService.spec.ts
Labels: 🐻‍❄️ 혁준 🐻‍❄️, ✅ Test

#117 방 퇴사하기 테스트
  test/RoomService.spec.ts
Labels: 🐻‍❄️ 혁준 🐻‍❄️, ✅ Test

#119 #118 [chore] 로그 파일 분리
  src/config/logger.ts
Labels: 🐻‍❄️ 혁준 🐻‍❄️, 🌏 Deploy

#122 규칙 테스트
  test/RuleService.spec.ts
Labels: 🐻‍❄️ 혁준 🐻‍❄️, ✅ Test

#121 #82 [feat] 규칙 홈 조회 api 구현
  src/controllers/RuleController.ts
  src/interfaces/room/HomeResponseDto.ts
  src/interfaces/rule/RuleHomeResponseDto.ts
  src/interfaces/rulecategory/RuleCategoryResponseDto.ts
  src/modules/responseMessage.ts
  src/routes/RoomRouter.ts
  src/services/RoomService.ts
  src/services/RuleService.ts
Labels: ✨ Feature, 🐣 혜정 🐣

#125 오늘 to-do 체크 변경 api 구현
  src/controllers/RuleController.ts
  src/interfaces/rule/RuleTodoCheckUpdateDto.ts
  src/interfaces/rule/RuleTodoCheckUpdateResponseDto.ts
  src/modules/responseMessage.ts
  src/routes/RoomRouter.ts
  src/services/RuleService.ts
Labels: ✨ Feature, 😸 연주 😸

#126 유저 알림 설정 api 수정
  src/controllers/UserController.ts
  src/interfaces/user/UserNotificationStateUpdateDto.ts
  src/interfaces/user/UsuerNotificationStateUpdateDto.ts
  src/services/UserService.ts
Labels: 😸 연주 😸, 🔧 Fix

#128 성향 관련 정렬 변경 - 성향테스트 유무에 따른 정렬
  src/services/RuleService.ts
Labels: 😸 연주 😸, 🔧 Fix

#129 [fix] 홈조회 및 이벤트 조회 시 클라가 원하는 형태로 response 변경
  src/interfaces/event/EventCreateResponseDto.ts
  src/interfaces/event/EventResponseDto.ts
  src/interfaces/event/EventUpdateResponseDto.ts
  src/interfaces/room/HomeResponseDto.ts
  src/services/EventService.ts
  src/services/RoomService.ts
Labels: 🔧 Fix, 🐣 혜정 🐣

#130 #124 [fix] 나의 todo 오름차순 정렬
  src/interfaces/rule/RuleMyTodoResponseDto.ts
  src/services/RuleService.ts
Labels: 🐻‍❄️ 혁준 🐻‍❄️, 🔧 Fix

#136 #58 [fix] 방 생성 시 가이드 규칙 추가
  src/services/RoomService.ts
Labels: 🐻‍❄️ 혁준 🐻‍❄️, 🔧 Fix

#133 #132 [feat] 성향 점수 등록 및 수정 api 구현
  src/controllers/UserController.ts
  src/interfaces/user/UserTypeTestDto.ts
  src/interfaces/user/UserTypeTestResponseDto.ts
  src/modules/responseMessage.ts
  src/routes/UserRouter.ts
  src/services/UserService.ts
Labels: ✨ Feature, 🐣 혜정 🐣

#135 Type 컬렉션 수정 및 TypeTest 컬렉션 추가
  src/interfaces/type/TypeInfo.ts
  src/interfaces/type/TypeTestInfo.ts
  src/models/Type.ts
  src/models/TypeTest.ts
Labels: ✨ Feature, 😸 연주 😸, 🔧 Fix

#139 TypeTest 컬렉션 수정
  src/loaders/db.ts
  src/models/Type.ts
  src/models/TypeTest.ts
Labels: 😸 연주 😸, 🔧 Fix

#142 #141 [feat] 성향 테스트 내용 조회 api 구현
  src/controllers/UserController.ts
  src/interfaces/user/response/UserTypeTestInfoResponseDto.ts
  src/modules/responseMessage.ts
  src/routes/UserRouter.ts
  src/services/user/UserRetrieveService.ts
Labels: ✨ Feature, 😸 연주 😸

#144 유저 탈퇴하기 api 구현 및 그 외 수정
  src/controllers/UserController.ts
  src/models/User.ts
  src/modules/responseMessage.ts
  src/routes/UserRouter.ts
  src/services/event/EventServiceUtils.ts
  src/services/room/RoomRetrieveService.ts
  src/services/room/RoomServiceUtils.ts
  src/services/rule/RuleServiceUtils.ts
  src/services/user/UserRetrieveService.ts
  src/services/user/UserService.ts
Labels: ✨ Feature, 🔧 Fix, 🐣 혜정 🐣

#147 [chore] 슬랙 500 에러 일 때, 알림 오도록 추가
  .github/workflows/deploy.yml
  package.json
  src/config/index.ts
  src/errors/generalErrorHandler.ts
  src/middleware/slackAlarm.ts
Labels: ⚙ Setting, 🐣 혜정 🐣

#150 GET body -> query 수정
  src/controllers/RoomController.ts
  src/routes/RoomRouter.ts
  src/services/room/RoomRetrieveService.ts
Labels: 🐻‍❄️ 혁준 🐻‍❄️, 🔧 Fix

#152 #151 [chore] CICD 환경 변경
  .github/workflows/deploy.yml
  scripts/after-deploy.sh
Labels: ⚙ Setting, 🐣 혜정 🐣

#156 [fix] 규칙 홈 조회 - 성향 테스트 한 사람은 앞으로 오름차순 정렬 / 안한 사람은 뒤로 변경
  src/services/rule/RuleRetrieveService.ts
Labels: 🔧 Fix, 🐣 혜정 🐣

#166 성향 상세 조회 (성향 결과 조회) response 형식 수정
  src/interfaces/type/TypeInfo.ts
  src/interfaces/type/response/TypeDetailResponseDto.ts
  src/models/Type.ts
  src/services/user/UserRetrieveService.ts
Labels: 😸 연주 😸, 🔧 Fix

#167 회원가입, 로그인 테스트
  test/AuthService.spec.ts
  test/RuleRetrieveService.spec.ts
  test/UserService.spec.ts
Labels: 🐻‍❄️ 혁준 🐻‍❄️, ✅ Test

#171 #170 [fix] D-Day 계산 수정
  src/services/room/RoomRetrieveService.ts
Labels: 🐻‍❄️ 혁준 🐻‍❄️, 🔧 Fix

#172 #170 [fix] D-0 도 포함하도록 수정
  src/services/room/RoomRetrieveService.ts
Labels: 🐻‍❄️ 혁준 🐻‍❄️, 🔧 Fix

#174 #173 [fix] event 추가/수정 시, date format 확인 추가
  src/routes/RoomRouter.ts
Labels: 🔧 Fix, 🐣 혜정 🐣

#178 #177 [fix] 기획 변경에 따라 해쉬태그 내 글자수 최대 4자로 변경
  src/modules/limitNum.ts
Labels: 🔧 Fix, 🐣 혜정 🐣

#183 Fix/182 fix type
  src/interfaces/type/response/TypeTestResponseDto.ts
  src/interfaces/user/response/HomieResponseDto.ts
  src/interfaces/user/response/UserProfileResponseDto.ts
  src/routes/RoomRouter.ts
  src/routes/UserRouter.ts
  src/services/room/RoomRetrieveService.ts
  src/services/user/UserRetrieveService.ts
  src/services/user/UserService.ts
  src/services/user/UserServiceUtils.ts
  swagger-output.json
Labels: 🔧 Fix, 🐣 혜정 🐣

#185 #184 [fix] 규칙 생성 시 조회, 생성, 조회에서 Response 수정
  src/interfaces/rule/response/RuleCreateInfoResponseDto.ts
  src/services/rule/RuleRetrieveService.ts
Labels: 😸 연주 😸, 🔧 Fix

#188 #187 [fix] 규칙 생성 에러 케이스 추가
  src/services/rule/RuleService.ts
Labels: 🐻‍❄️ 혁준 🐻‍❄️, 🔧 Fix

#189 성향 테스트 조회 test 코드 작성
  src/controllers/UserController.ts
  test/TypeRetrieveService.spec.ts
Labels: 😸 연주 😸, ✅ Test

#190 사용자 관련 테스트 코드 작성 및 오류 수정
  src/services/user/UserRetrieveService.ts
  src/services/user/UserService.ts
  src/services/user/UserServiceUtils.ts
  test/UserRetrieveService.spec.ts
  test/UserService.spec.ts
Labels: 🔧 Fix, 🐣 혜정 🐣, ✅ Test

#196 #195 [fix] 오타수정
  src/services/event/EventRetrieveService.ts
  src/services/room/RoomRetrieveService.ts
Labels: 🔧 Fix, 🐣 혜정 🐣

#203 #202 [fix] 홈조회 시 임시담당자 조건문 변수 수정
  src/services/room/RoomRetrieveService.ts
Labels: 🔧 Fix, 🐣 혜정 🐣

#204 [fix] 상단 규칙 및 규칙들 최대 5개까지만 보이도록 수정
  src/modules/limitNum.ts
  src/services/room/RoomRetrieveService.ts
Labels: 🔧 Fix, 🐣 혜정 🐣

#200 이벤트 관련 api 테스트 추가
  test/EventRetrieveService.spec.ts
  test/EventService.spec.ts
Labels: 🐣 혜정 🐣, ✅ Test

#205 RuleService -규칙 카테고리 테스트 코드
  test/RuleService.spec.ts
Labels: 😸 연주 😸, ✅ Test

#207 규칙 홈 및 홈 조회 테스트
  test/EventRetrieveService.spec.ts
  test/EventService.spec.ts
  test/RoomRetrieveService.spec.ts
  test/RoomService.spec.ts
  test/RuleRetrieveService.spec.ts
  test/RuleService.spec.ts
  test/TypeRetrieveService.spec.ts
  test/UserRetrieveService.spec.ts
Labels: 🐣 혜정 🐣, ✅ Test

#209 RuleRetrieveService -규칙 관련 조회 테스트 코드
  test/RuleRetrieveService.spec.ts
  test/RuleService.spec.ts
Labels: 😸 연주 😸, ✅ Test

#213 임시 담당자 설정 시 조회 테스트
  src/routes/RoomRouter.ts
  test/RuleService.spec.ts
Labels: 😸 연주 😸, ✅ Test

#214 오늘 나의 to-do 체크 상태 변경하기 / 오늘의 임시 담당자 설정하기 조회 테스트
  test/RuleRetrieveService.spec.ts
  test/RuleService.spec.ts
Labels: 🐣 혜정 🐣, ✅ Test

#217 #216 [fix] ruleMember userId validation 수정
  src/services/rule/RuleService.ts
Labels: 🐻‍❄️ 혁준 🐻‍❄️, 🔧 Fix

#218 #216 [fix] createRule 수정
  src/services/rule/RuleService.ts
Labels: 🐻‍❄️ 혁준 🐻‍❄️, 🔧 Fix

#220 규칙 홈 화면 버그 수정
  .github/workflows/pr-check.yml
  .husky/pre-push
  package.json
  src/controllers/AuthController.ts
  src/controllers/EventController.ts
  src/controllers/RoomController.ts
  src/controllers/RuleController.ts
  src/controllers/UserController.ts
  src/services/rule/RuleRetrieveService.ts
Labels: 🔧 Fix, 🐣 혜정 🐣

#215 허스키 환경 구축
  .husky/pre-commit
  .husky/pre-push
  package.json
Labels: ⚙ Setting, 🐣 혜정 🐣

#223 규칙 카테고리별 규칙 리스트 조회 시 멤버 수 카운트 로직 수정
  src/services/rule/RuleRetrieveService.ts
Labels: 😸 연주 😸, 🔧 Fix

#225 홈뷰 이벤트 / 성향 테스트 정렬 오름차순 추가
  src/services/room/RoomRetrieveService.ts
  src/services/type/TypeRetrieveService.ts
Labels: 🔧 Fix, 🐣 혜정 🐣

#228 #224 [fix] 성향테스트 등록 및 수정 시 typeUpdatedDate 변경 부분 추가
  src/interfaces/room/response/HomeResponseDto.ts
  src/services/event/EventService.ts
  src/services/room/RoomRetrieveService.ts
  src/services/user/UserService.ts
Labels: 🔧 Fix, 🐣 혜정 🐣

#231 #230 [fix] 홈 뷰에서 todo 2개 보이는 문제 해결
  src/services/room/RoomRetrieveService.ts
Labels: 🔧 Fix, 🐣 혜정 🐣

#232 #230 [fix] 규칙 홈화면 오늘이 아닌 규칙도 보여주는 문제 해결
  src/services/rule/RuleRetrieveService.ts
Labels: 🔧 Fix, 🐣 혜정 🐣
